<?php

declare(strict_types=1);

if (!function_exists('isRunningInDocker')) {
    /**
     * Determine if the application is running in a Docker container.
     *
     * Code generated by Anthropic Claude using the following prompt:
     * "How can I detect in PHP whether we're currently running inside Docker?"
     *
     * @return bool
     */
    function isRunningInDocker(): bool
    {
        // Method 1: Check for .dockerenv file
        if (file_exists('/.dockerenv')) {
            return true;
        }

        // Method 2: Check cgroup for docker
        if (file_exists('/proc/1/cgroup')) {
            $contents = file_get_contents('/proc/1/cgroup');
            if (str_contains($contents, 'docker')) {
                return true;
            }
        }

        // Method 3: Check for docker as hostname
        $hostname = gethostname();
        if ($hostname && preg_match('/^[a-f0-9]{12}$/', $hostname)) {
            return true;
        }

        return false;
    }
}

return [
    /*
     *  The host used to communicate with the Ray app.
     */
    'host' => isRunningInDocker() ? 'host.docker.internal' : 'localhost',

    /*
     *  The port number used to communicate with the Ray app.
     */
    'port' => 23517,

    /*
     *  Absolute base path for your sites or projects in Homestead, Vagrant, Docker, or another remote development server.
     */
    'remote_path' => '/var/www/html',

    /*
     *  Absolute base path for your sites or projects on your local computer where your IDE or code editor is running on.
     */
    'local_path' => __DIR__,
];
